### ISSUE TITLE
Avoid Window popup

### ISSUE THREAD

**Issue by juliensobrier** [sdesalas/trifleJS#45]
Websites can open window popus. See the fix at https://github.com/juliensobrier/trifleJS/commit/df345c550e1434ef71f90ee27b0f0f9c3517f021:

this.NewWindow += delegate(object sender, System.ComponentModel.CancelEventArgs e)
 {
 e.Cancel = true; ;
 };

**Comment by sdesalas** [comment]
Hi @juliensobrier, thanks for the suggestion.

I did wonder what to do about popups when I was working on window frames. Not sure I feel that great about banishing them entirely but your code is useful and I'm leaning towards having a solution here where this is a CLI option rather than outright default setting. I believe original PhantomJS allows for popups as well as navigation from child to parent and backwards.

**Comment by sdesalas** [comment]
Added CLI option `--ingore-popups` for this.
